"""empty message

Revision ID: e0bf40c92007
Revises: cc8e4c727779
Create Date: 2023-02-06 18:23:17.548026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0bf40c92007'
down_revision = 'cc8e4c727779'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('treatment_machine', schema=None) as batch_op:
        batch_op.alter_column('energy',
               existing_type=sa.FLOAT(),
               type_=sa.String(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('treatment_machine', schema=None) as batch_op:
        batch_op.alter_column('energy',
               existing_type=sa.String(length=100),
               type_=sa.FLOAT(),
               existing_nullable=False)

    # ### end Alembic commands ###
